name       : haskell-attoparsec-iso8601
version    : 1.0.1.0
release    : 2
source     :
    - https://hackage.haskell.org/package/attoparsec-iso8601-1.0.1.0/attoparsec-iso8601-1.0.1.0.tar.gz : 499ffbd2d39e79cc4fda5ad0129dbf94fdb72a84aa932dfe2a5f5c5c02074142
license    : BSD-3-Clause
component  : programming.haskell
summary    : Parsing of ISO 8601 dates, originally from aeson.
description: |
    Parsing of ISO 8601 dates, originally from aeson.
builddeps  :
    - haskell-attoparsec-devel
    - haskell-base-compat-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-attoparsec-devel
        - haskell-base-compat-devel
networking : yes
setup      : |
    sed -i "s|< 0.11|< 0.12|g" attoparsec-iso8601.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
