name       : haskell-attoparsec-iso8601
version    : 1.0.0.0
release    : 1
source     :
    - https://hackage.haskell.org/package/attoparsec-iso8601-1.0.0.0/attoparsec-iso8601-1.0.0.0.tar.gz : aa6c6d87587383e386cb85e7ffcc4a6317aa8dafb8ba9a104ecac365ce2a858a
license    : BSD-3-Clause
component  : programming.haskell
summary    : Parsing of ISO 8601 dates, originally from aeson.
description: |
    Parsing of ISO 8601 dates, originally from aeson.
builddeps  :
    - haskell-attoparsec
    - haskell-base-compat
    - haskell-cabal-install
    - haskell-text
setup      : |
    sed -i "s|0.10|0.11|g" attoparsec-iso8601.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
